# Generated by Django 5.2 on 2025-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=50)),
                ('payload_1', models.FloatField()),
                ('payload_2', models.FloatField()),
                ('payload_3', models.FloatField()),
                ('payload_4', models.FloatField()),
                ('payload_5', models.FloatField()),
                ('payload_6', models.FloatField()),
                ('payload_7', models.FloatField()),
                ('payload_8', models.FloatField()),
                ('payload_9', models.FloatField()),
                ('payload_10', models.FloatField()),
                ('cost', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
