# Generated by Django 5.2 on 2025-04-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
